# Generated by Django 4.1.7 on 2023-03-13 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_contact_firstname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='firstName',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
